version: '2.1'

services:
  elr-Backend:
    image: elrws
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 3001:3001
      - 5005:5005
    