logging:
  level:
    # org.springframework.web: DEBUG
    org.springframework: DEBUG
    elr.ws.elrws: DEBUG

server:
    port: 3100

spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"

